### ISSUE TITLE
Make revisions to module one based on feedback.

### ISSUE THREAD

**Issue by ryan-whit** [ryan-whit/bootcamp-hwk-rwhitmore#7]
Things to consider:

- [x] The "Search Engine Optimization" nav link is not functional. That section is missing the corresponding id. Refer to your other two for reference.
- [x] The CSS selectors and properties are not consolidated. Instead of having multiple selectors with the same properties such as:

```css
.benefit-lead {
    margin-bottom: 32px;
    color: #ffffff;
}

.benefit-brand {
    margin-bottom: 32px;
    color: #ffffff;
}

.benefit-cost {
    margin-bottom: 32px;
    color: #ffffff;
}
```

It's best to have 1:
```css
.benefit {
    margin-bottom: 32px;
    color: #ffffff;
}
```

- [x] don't forget to update the corresponding classes in the HTML file and condense the rest similarly
- [x] The repo is missing the README with the description, screenshot, and deployed link to the application.
- [x] The hero image is missing from the deployed application.
